// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	fmt "fmt"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	validator "github.com/hyperledger/burrow/acm/validator"
	bcm "github.com/hyperledger/burrow/bcm"
	github_com_hyperledger_burrow_binary "github.com/hyperledger/burrow/binary"
	tendermint "github.com/hyperledger/burrow/consensus/tendermint"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ResultStatus struct {
	ChainID       string                                        `protobuf:"bytes,1,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	RunID         string                                        `protobuf:"bytes,2,opt,name=RunID,proto3" json:"RunID,omitempty"`
	BurrowVersion string                                        `protobuf:"bytes,3,opt,name=BurrowVersion,proto3" json:"BurrowVersion,omitempty"`
	GenesisHash   github_com_hyperledger_burrow_binary.HexBytes `protobuf:"bytes,4,opt,name=GenesisHash,proto3,customtype=github.com/hyperledger/burrow/binary.HexBytes" json:"GenesisHash"`
	NodeInfo      *tendermint.NodeInfo                          `protobuf:"bytes,5,opt,name=NodeInfo,proto3" json:"NodeInfo,omitempty"`
	SyncInfo      *bcm.SyncInfo                                 `protobuf:"bytes,6,opt,name=SyncInfo,proto3" json:"SyncInfo,omitempty"`
	// When catching up in fast sync
	CatchingUp           bool                 `protobuf:"varint,8,opt,name=CatchingUp,proto3" json:""`
	ValidatorInfo        *validator.Validator `protobuf:"bytes,7,opt,name=ValidatorInfo,proto3" json:"ValidatorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResultStatus) Reset()         { *m = ResultStatus{} }
func (m *ResultStatus) String() string { return proto.CompactTextString(m) }
func (*ResultStatus) ProtoMessage()    {}
func (*ResultStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}
func (m *ResultStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultStatus.Unmarshal(m, b)
}
func (m *ResultStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultStatus.Marshal(b, m, deterministic)
}
func (m *ResultStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultStatus.Merge(m, src)
}
func (m *ResultStatus) XXX_Size() int {
	return xxx_messageInfo_ResultStatus.Size(m)
}
func (m *ResultStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResultStatus proto.InternalMessageInfo

func (m *ResultStatus) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *ResultStatus) GetRunID() string {
	if m != nil {
		return m.RunID
	}
	return ""
}

func (m *ResultStatus) GetBurrowVersion() string {
	if m != nil {
		return m.BurrowVersion
	}
	return ""
}

func (m *ResultStatus) GetNodeInfo() *tendermint.NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *ResultStatus) GetSyncInfo() *bcm.SyncInfo {
	if m != nil {
		return m.SyncInfo
	}
	return nil
}

func (m *ResultStatus) GetCatchingUp() bool {
	if m != nil {
		return m.CatchingUp
	}
	return false
}

func (m *ResultStatus) GetValidatorInfo() *validator.Validator {
	if m != nil {
		return m.ValidatorInfo
	}
	return nil
}

func (*ResultStatus) XXX_MessageName() string {
	return "rpc.ResultStatus"
}
func init() {
	proto.RegisterType((*ResultStatus)(nil), "rpc.ResultStatus")
	golang_proto.RegisterType((*ResultStatus)(nil), "rpc.ResultStatus")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }
func init() { golang_proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbf, 0x6e, 0xea, 0x30,
	0x18, 0xc5, 0x31, 0x7f, 0x83, 0x01, 0xdd, 0x2b, 0x8b, 0x21, 0x62, 0x08, 0xb9, 0x57, 0x0c, 0xb9,
	0xc3, 0x4d, 0xaa, 0xa2, 0x2e, 0x1d, 0x43, 0xa5, 0xc2, 0xd2, 0xc1, 0xa8, 0x54, 0xea, 0x96, 0x3f,
	0x6e, 0x62, 0x09, 0xec, 0xc8, 0x71, 0xda, 0xe6, 0xed, 0x3a, 0xf2, 0x08, 0x55, 0x07, 0x54, 0xc1,
	0xd6, 0x67, 0xe8, 0x50, 0x61, 0x08, 0x85, 0xa5, 0xdb, 0x77, 0x7e, 0xe7, 0xfb, 0x8e, 0xac, 0x63,
	0xd8, 0x14, 0x49, 0x60, 0x27, 0x82, 0x4b, 0x8e, 0x2a, 0x22, 0x09, 0x7a, 0xdd, 0x88, 0x47, 0x5c,
	0x69, 0x67, 0x3b, 0xed, 0xac, 0xde, 0x6f, 0x49, 0x58, 0x48, 0xc4, 0x82, 0x32, 0xb9, 0x27, 0xbf,
	0x1e, 0xbd, 0x39, 0x0d, 0x3d, 0xc9, 0xc5, 0x1e, 0x34, 0xfd, 0x60, 0xb1, 0x1b, 0xff, 0x7e, 0x96,
	0x61, 0x1b, 0x93, 0x34, 0x9b, 0xcb, 0xa9, 0xf4, 0x64, 0x96, 0x22, 0x1d, 0x36, 0x46, 0xb1, 0x47,
	0xd9, 0xe4, 0x4a, 0x07, 0x26, 0xb0, 0x9a, 0xb8, 0x90, 0xa8, 0x0b, 0x6b, 0x38, 0xdb, 0xf2, 0xb2,
	0xe2, 0x3b, 0x81, 0x06, 0xb0, 0xe3, 0x66, 0x42, 0xf0, 0xa7, 0x19, 0x11, 0x29, 0xe5, 0x4c, 0xaf,
	0x28, 0xf7, 0x14, 0xa2, 0x3b, 0xd8, 0xba, 0x26, 0x8c, 0xa4, 0x34, 0x1d, 0x7b, 0x69, 0xac, 0x57,
	0x4d, 0x60, 0xb5, 0xdd, 0x8b, 0xe5, 0xaa, 0x5f, 0x7a, 0x5b, 0xf5, 0xff, 0x47, 0x54, 0xc6, 0x99,
	0x6f, 0x07, 0x7c, 0xe1, 0xc4, 0x79, 0x42, 0xc4, 0x9c, 0x84, 0x11, 0x11, 0x8e, 0xaf, 0x22, 0x1c,
	0x9f, 0x32, 0x4f, 0xe4, 0xf6, 0x98, 0x3c, 0xbb, 0xb9, 0x24, 0x29, 0x3e, 0x4e, 0x42, 0x67, 0x50,
	0xbb, 0xe1, 0x21, 0x99, 0xb0, 0x07, 0xae, 0xd7, 0x4c, 0x60, 0xb5, 0xce, 0xbb, 0xf6, 0x51, 0x01,
	0x85, 0x87, 0x0f, 0x5b, 0xe8, 0x1f, 0xd4, 0xa6, 0x39, 0x0b, 0xd4, 0x45, 0x5d, 0x5d, 0x74, 0xec,
	0x6d, 0x1f, 0x05, 0xc4, 0x07, 0x1b, 0x0d, 0x20, 0x1c, 0x79, 0x32, 0x88, 0x29, 0x8b, 0x6e, 0x13,
	0x5d, 0x33, 0x81, 0xa5, 0xb9, 0xd5, 0x8f, 0x55, 0xbf, 0x84, 0x8f, 0x38, 0xba, 0x84, 0x9d, 0x59,
	0x51, 0xb0, 0x4a, 0x6d, 0xec, 0xdf, 0xf1, 0x5d, 0xfb, 0xc1, 0xc7, 0xa7, 0xab, 0xee, 0xf0, 0x75,
	0x6d, 0x80, 0xf7, 0xb5, 0x01, 0x5e, 0x36, 0x06, 0x58, 0x6e, 0x0c, 0x70, 0xff, 0xe7, 0xe7, 0x32,
	0x44, 0x12, 0xf8, 0x75, 0xf5, 0x75, 0xc3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x6c, 0x69,
	0x76, 0x10, 0x02, 0x00, 0x00,
}

func (m *ResultStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	l = len(m.RunID)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	l = len(m.BurrowVersion)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	l = m.GenesisHash.Size()
	n += 1 + l + sovRpc(uint64(l))
	if m.NodeInfo != nil {
		l = m.NodeInfo.Size()
		n += 1 + l + sovRpc(uint64(l))
	}
	if m.SyncInfo != nil {
		l = m.SyncInfo.Size()
		n += 1 + l + sovRpc(uint64(l))
	}
	if m.CatchingUp {
		n += 2
	}
	if m.ValidatorInfo != nil {
		l = m.ValidatorInfo.Size()
		n += 1 + l + sovRpc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovRpc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRpc(x uint64) (n int) {
	return sovRpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
