// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint.proto

package tendermint

import (
	fmt "fmt"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	github_com_hyperledger_burrow_binary "github.com/hyperledger/burrow/binary"
	github_com_hyperledger_burrow_crypto "github.com/hyperledger/burrow/crypto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NodeInfo struct {
	ID                   github_com_hyperledger_burrow_crypto.Address  `protobuf:"bytes,1,opt,name=ID,proto3,customtype=github.com/hyperledger/burrow/crypto.Address" json:"ID"`
	ListenAddress        string                                        `protobuf:"bytes,2,opt,name=ListenAddress,proto3" json:"ListenAddress,omitempty"`
	Network              string                                        `protobuf:"bytes,3,opt,name=Network,proto3" json:"Network,omitempty"`
	Version              string                                        `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	Channels             github_com_hyperledger_burrow_binary.HexBytes `protobuf:"bytes,5,opt,name=Channels,proto3,customtype=github.com/hyperledger/burrow/binary.HexBytes" json:"Channels"`
	Moniker              string                                        `protobuf:"bytes,6,opt,name=Moniker,proto3" json:"Moniker,omitempty"`
	RPCAddress           string                                        `protobuf:"bytes,7,opt,name=RPCAddress,proto3" json:"RPCAddress,omitempty"`
	TxIndex              string                                        `protobuf:"bytes,8,opt,name=TxIndex,proto3" json:"TxIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{0}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetListenAddress() string {
	if m != nil {
		return m.ListenAddress
	}
	return ""
}

func (m *NodeInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NodeInfo) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *NodeInfo) GetRPCAddress() string {
	if m != nil {
		return m.RPCAddress
	}
	return ""
}

func (m *NodeInfo) GetTxIndex() string {
	if m != nil {
		return m.TxIndex
	}
	return ""
}

func (*NodeInfo) XXX_MessageName() string {
	return "tendermint.NodeInfo"
}
func init() {
	proto.RegisterType((*NodeInfo)(nil), "tendermint.NodeInfo")
	golang_proto.RegisterType((*NodeInfo)(nil), "tendermint.NodeInfo")
}

func init() { proto.RegisterFile("tendermint.proto", fileDescriptor_04f926c8da23c367) }
func init() { golang_proto.RegisterFile("tendermint.proto", fileDescriptor_04f926c8da23c367) }

var fileDescriptor_04f926c8da23c367 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3d, 0x4f, 0x3a, 0x41,
	0x10, 0xc6, 0xff, 0x7b, 0x7f, 0x05, 0xdc, 0x68, 0x62, 0x2e, 0x16, 0x1b, 0x8b, 0x83, 0x18, 0x0b,
	0x0a, 0xbd, 0x4b, 0x7c, 0xf9, 0x00, 0xc2, 0x15, 0x5e, 0xa2, 0x44, 0x2f, 0xc6, 0xc2, 0x8e, 0xe3,
	0xc6, 0x63, 0x03, 0xec, 0x90, 0xd9, 0x25, 0x70, 0xdf, 0xce, 0x92, 0xd6, 0xce, 0x58, 0x10, 0x03,
	0x5f, 0xc4, 0xdc, 0x0b, 0xa2, 0x8d, 0x76, 0xfb, 0xfc, 0x9e, 0x9d, 0x9d, 0x67, 0x67, 0xf8, 0xbe,
	0x01, 0x15, 0x03, 0x8d, 0xa4, 0x32, 0xee, 0x98, 0xd0, 0xa0, 0xcd, 0x37, 0xe4, 0xf0, 0x20, 0xc1,
	0x04, 0x73, 0xec, 0x65, 0xa7, 0xe2, 0xc6, 0xd1, 0xab, 0xc5, 0x6b, 0x1d, 0x8c, 0x21, 0x50, 0xcf,
	0x68, 0xfb, 0xdc, 0x0a, 0x7c, 0xc1, 0x1a, 0xac, 0xb9, 0xdb, 0xba, 0x98, 0x2f, 0xea, 0xff, 0xde,
	0x17, 0xf5, 0x93, 0x44, 0x9a, 0xfe, 0x24, 0x72, 0x7b, 0x38, 0xf2, 0xfa, 0xe9, 0x18, 0x68, 0x08,
	0x71, 0x02, 0xe4, 0x45, 0x13, 0x22, 0x9c, 0x7a, 0x3d, 0x4a, 0xc7, 0x06, 0xdd, 0xab, 0x38, 0x26,
	0xd0, 0x3a, 0xb4, 0x02, 0xdf, 0x3e, 0xe6, 0x7b, 0x37, 0x52, 0x1b, 0x50, 0x25, 0x14, 0x56, 0x83,
	0x35, 0x77, 0xc2, 0x9f, 0xd0, 0x16, 0xbc, 0xda, 0x01, 0x33, 0x45, 0x1a, 0x88, 0xff, 0xb9, 0xbf,
	0x96, 0x99, 0xf3, 0x08, 0xa4, 0x25, 0x2a, 0xb1, 0x55, 0x38, 0xa5, 0xb4, 0xef, 0x79, 0xad, 0xdd,
	0xef, 0x2a, 0x05, 0x43, 0x2d, 0xb6, 0xf3, 0x94, 0x97, 0x65, 0xca, 0xd3, 0xdf, 0x53, 0x46, 0x52,
	0x75, 0x29, 0x75, 0xaf, 0x61, 0xd6, 0x4a, 0x0d, 0xe8, 0xf0, 0xeb, 0x99, 0xac, 0xd9, 0x2d, 0x2a,
	0x39, 0x00, 0x12, 0x95, 0xa2, 0x59, 0x29, 0x6d, 0x87, 0xf3, 0xf0, 0xae, 0xbd, 0xfe, 0x43, 0x35,
	0x37, 0xbf, 0x91, 0xac, 0xf2, 0x61, 0x16, 0xa8, 0x18, 0x66, 0xa2, 0x56, 0x54, 0x96, 0xb2, 0xe5,
	0xbf, 0x2d, 0x1d, 0xf6, 0xb1, 0x74, 0xd8, 0xcb, 0xca, 0x61, 0xf3, 0x95, 0xc3, 0x9e, 0xce, 0xfe,
	0x18, 0x22, 0x2a, 0x0d, 0x4a, 0x4f, 0xb4, 0xb7, 0xd9, 0x57, 0x54, 0xc9, 0x17, 0x74, 0xfe, 0x19,
	0x00, 0x00, 0xff, 0xff, 0x2a, 0xed, 0x5e, 0xe2, 0xd6, 0x01, 0x00, 0x00,
}

func (m *NodeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovTendermint(uint64(l))
	l = len(m.ListenAddress)
	if l > 0 {
		n += 1 + l + sovTendermint(uint64(l))
	}
	l = len(m.Network)
	if l > 0 {
		n += 1 + l + sovTendermint(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovTendermint(uint64(l))
	}
	l = m.Channels.Size()
	n += 1 + l + sovTendermint(uint64(l))
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovTendermint(uint64(l))
	}
	l = len(m.RPCAddress)
	if l > 0 {
		n += 1 + l + sovTendermint(uint64(l))
	}
	l = len(m.TxIndex)
	if l > 0 {
		n += 1 + l + sovTendermint(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTendermint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTendermint(x uint64) (n int) {
	return sovTendermint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
